---

git_url: "https://github.com/jopohl/urh.git"

deps_packages:
  - python3 
  - python3-pip 
  - python3-virtualenv
  - python3-setuptools
  - python3-pyqt5
  - qt5-qmake

pips_packages:
  - cython

bin_path: "/usr/local/bin/urh"
venv: "/usr/local/env-urh"
