version: '3'

services:
  builder:
    build:
      context: .
    container_name: raspi_hackbox
    privileged: true
    deploy:
      resources:
        reservations:
         cpus: '0.50'
         memory: 4G
        - /dev:/dev
    command: rpi4_trixie.img
